apply plugin: 'idea'
idea.module.inheritOutputDirs = true

buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net/' }
        mavenCentral()
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:5.1.48'
    }
}

apply plugin: 'net.minecraftforge.gradle'
// Only edit below this line, the above code adds and enables the necessary things for Forge to be setup.
apply plugin: 'eclipse'
apply plugin: 'maven-publish'

version = "forge-mc${project.minecraft_version}-${project.version}"
group = project.maven_group
archivesBaseName = project.archives_base_name

sourceCompatibility = targetCompatibility = compileJava.sourceCompatibility = compileJava.targetCompatibility = '1.8' // Need this here so eclipse task generates correctly.

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
    
minecraft {
    mappings channel: 'stable', version: '39-1.12'

    runs {
        client {
            workingDirectory project.file('run_client')
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', 'debug'
            property 'fml.coreMods.load', 'gloomyfolken.hooklib.minecraft.MainHookLoader'
        }

        server {
            workingDirectory project.file('run_server')
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', 'debug'
            property 'fml.coreMods.load', 'gloomyfolken.hooklib.minecraft.MainHookLoader'
        }
    }
}

repositories {
    flatDir {
        dirs "${project.rootDir}/libs"
    }
    flatDir {
        dirs 'F:\\Development\\modding\\_artifacts_'
    }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.12.2-14.23.5.2860'

    implementation "_ABC:hooklib:+"
}

jar {
	from('LICENSE') {
		rename { "${it}_${base.archivesName.get()}" }
	}

    destinationDirectory = file("$rootDir/production")
}

jar.finalizedBy('reobfJar')

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact jar
			from components.java
        }
    }
    repositories {
        maven {
            url "file:///${project.projectDir}/mcmodsrepo"
        }
    }
}