name: Release build

permissions:
  contents: write

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1

    - name: Setup Java JDK
      uses: actions/setup-java@v4.0.0
      with:
        java-version: 8
        distribution: 'zulu'
    
    - name: Show Working directory
      run: ls
    
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew -Dorg.gradle.jvmargs=-Xmx3G build
    
    - uses: softprops/action-gh-release@v2
      with:
          files: |
            production/alternate-current-forge-mc1.12.2-*.jar
